"""
React/TypeScript Generator for Spacing Tokens

Generates TypeScript exports for React applications.
Follows the pattern of react_generator.py for color tokens.
"""

from copy_that.generators.library_models import SpacingTokenLibrary

from .base_generator import BaseGenerator


class SpacingReactGenerator(BaseGenerator):
    """
    Generate React/TypeScript exports for spacing tokens.

    Creates TypeScript interfaces and grouped exports for use in React apps.

    Example output:
    // Spacing Token Types
    export interface SpacingToken {
      value_px: number;
      value_rem: number;
      name: string;
      role?: string;
      grid_aligned?: boolean;
    }

    // Spacing Tokens
    export const spacing = {
      xs: { value_px: 4, value_rem: 0.25, name: 'spacing-xs', role: 'xs' },
      sm: { value_px: 8, value_rem: 0.5, name: 'spacing-sm', role: 'sm' },
      ...
    } as const;
    """

    def __init__(
        self,
        library: SpacingTokenLibrary,
        include_types: bool = True,
        include_metadata: bool = True,
        export_name: str = "spacing",
    ):
        """
        Initialize the React generator.

        Args:
            library: SpacingTokenLibrary to generate from
            include_types: Include TypeScript interface definitions
            include_metadata: Include confidence and provenance data
            export_name: Name for the main export
        """
        self.library = library
        self.include_types = include_types
        self.include_metadata = include_metadata
        self.export_name = export_name

    def generate(self) -> str:
        """
        Generate TypeScript exports.

        Returns:
            TypeScript string with interfaces and exports
        """
        lines = []

        # Header
        lines.append("/**")
        lines.append(" * Spacing Token Library")
        lines.append(
            f" * Generated by Copy That - {self.library.statistics.get('spacing_count', 0)} tokens"
        )
        lines.append(f" * Scale system: {self.library.statistics.get('scale_system', 'custom')}")
        lines.append(f" * Base unit: {self.library.statistics.get('base_unit', 8)}px")
        lines.append(" */")
        lines.append("")

        # Type definitions
        if self.include_types:
            lines.extend(self._generate_types())
            lines.append("")

        # Main exports
        lines.extend(self._generate_exports())

        # Helper functions
        lines.append("")
        lines.extend(self._generate_helpers())

        return "\n".join(lines)

    def _generate_types(self) -> list[str]:
        """Generate TypeScript interface definitions."""
        lines = []

        lines.append("// Spacing Token Types")
        lines.append("export interface SpacingToken {")
        lines.append("  value_px: number;")
        lines.append("  value_rem: number;")
        lines.append("  name: string;")
        lines.append("  role?: string;")
        lines.append("  semantic_role?: string;")
        lines.append("  grid_aligned?: boolean;")

        if self.include_metadata:
            lines.append("  confidence?: number;")
            lines.append("  provenance?: Record<string, number>;")

        lines.append("}")
        lines.append("")

        lines.append("export type SpacingKey = keyof typeof spacing;")

        return lines

    def _generate_exports(self) -> list[str]:
        """Generate token exports."""
        lines = []

        lines.append("// Spacing Tokens")
        lines.append(f"export const {self.export_name} = {{")

        for token in self.library.tokens:
            key = self._get_token_key(token)

            # Build token object
            token_props = [
                f"value_px: {token.value_px}",
                f"value_rem: {token.value_rem}",
                f"name: '{token.name}'",
            ]

            if token.role:
                token_props.append(f"role: '{token.role}'")

            if token.semantic_role:
                token_props.append(f"semantic_role: '{token.semantic_role}'")

            if token.grid_aligned is not None:
                token_props.append(f"grid_aligned: {str(token.grid_aligned).lower()}")

            if self.include_metadata:
                if token.confidence:
                    token_props.append(f"confidence: {round(token.confidence, 3)}")
                if token.provenance:
                    prov_str = ", ".join(f"'{k}': {v}" for k, v in token.provenance.items())
                    token_props.append(f"provenance: {{ {prov_str} }}")

            token_str = ", ".join(token_props)
            lines.append(f"  {key}: {{ {token_str} }},")

        lines.append("} as const;")

        return lines

    def _generate_helpers(self) -> list[str]:
        """Generate helper functions."""
        lines = []

        lines.append("// Helper functions")
        lines.append("")

        # Get spacing value
        lines.append("/**")
        lines.append(" * Get spacing value in pixels")
        lines.append(" */")
        lines.append("export function getSpacing(key: SpacingKey): number {")
        lines.append(f"  return {self.export_name}[key].value_px;")
        lines.append("}")
        lines.append("")

        # Get rem value
        lines.append("/**")
        lines.append(" * Get spacing value in rem")
        lines.append(" */")
        lines.append("export function getSpacingRem(key: SpacingKey): number {")
        lines.append(f"  return {self.export_name}[key].value_rem;")
        lines.append("}")
        lines.append("")

        # Get CSS variable
        lines.append("/**")
        lines.append(" * Get CSS variable name for spacing")
        lines.append(" */")
        lines.append("export function getSpacingVar(key: SpacingKey): string {")
        lines.append("  return `var(--spacing-${key})`;")
        lines.append("}")
        lines.append("")

        # All tokens array
        lines.append("/**")
        lines.append(" * Array of all spacing tokens")
        lines.append(" */")
        lines.append(f"export const spacingTokens = Object.values({self.export_name});")
        lines.append("")

        # Scale info
        lines.append("/**")
        lines.append(" * Spacing scale metadata")
        lines.append(" */")
        lines.append("export const spacingScale = {")
        lines.append(f"  system: '{self.library.statistics.get('scale_system', 'custom')}',")
        lines.append(f"  baseUnit: {self.library.statistics.get('base_unit', 8)},")
        lines.append(f"  count: {self.library.statistics.get('spacing_count', 0)},")
        lines.append(f"  gridCompliance: {self.library.statistics.get('grid_compliance', 0)},")
        lines.append("} as const;")

        return lines

    def _get_token_key(self, token) -> str:
        """
        Generate a valid TypeScript key for a token.

        Args:
            token: AggregatedSpacingToken

        Returns:
            Safe string for use as object key
        """
        # Prefer role if assigned
        if token.role:
            key = token.role
        elif token.name:
            # Extract key from name
            key = token.name.replace("spacing-", "").replace("space-", "")
        else:
            key = str(token.value_px)

        # Ensure valid identifier
        key = key.replace("-", "_").replace(" ", "_")

        # If starts with number, prefix with underscore
        if key and key[0].isdigit():
            key = f"_{key}"

        return key

    def generate_css_in_js(self) -> str:
        """
        Generate CSS-in-JS compatible exports (styled-components, emotion).

        Returns:
            TypeScript string with CSS-in-JS helpers
        """
        lines = []

        lines.append("/**")
        lines.append(" * CSS-in-JS Spacing Helpers")
        lines.append(" */")
        lines.append("")

        # Theme object
        lines.append("export const theme = {")
        lines.append("  spacing: {")

        for token in self.library.tokens:
            key = self._get_token_key(token)
            lines.append(f"    {key}: '{token.value_px}px',")

        lines.append("  },")
        lines.append("  spacingRem: {")

        for token in self.library.tokens:
            key = self._get_token_key(token)
            lines.append(f"    {key}: '{token.value_rem}rem',")

        lines.append("  },")
        lines.append("} as const;")
        lines.append("")

        # Helper for styled-components
        lines.append("// Styled-components helper")
        lines.append("export const sp = {")
        for token in self.library.tokens:
            key = self._get_token_key(token)
            lines.append(f"  {key}: `${{theme.spacing.{key}}}`,")
        lines.append("} as const;")

        return "\n".join(lines)
