import json

from copy_that.generators import (
    CSSTokenGenerator,
    HTMLDemoGenerator,
    ReactTokenGenerator,
    SpacingCSSGenerator,
    SpacingReactGenerator,
    SpacingW3CGenerator,
)
from copy_that.generators.library_models import (
    AggregatedColorToken,
    AggregatedSpacingToken,
    SpacingTokenLibrary,
    TokenLibrary,
)


def _build_color_library() -> TokenLibrary:
    token = AggregatedColorToken(
        hex="#FF0000",
        rgb="rgb(255,0,0)",
        name="Primary Accent",
        confidence=0.85,
        provenance={"image_1": 0.85},
        role="primary",
    )
    library = TokenLibrary(
        tokens=[token], statistics={"color_count": 1, "avg_confidence": 0.85, "image_count": 1}
    )
    return library


def _build_spacing_library() -> SpacingTokenLibrary:
    token = AggregatedSpacingToken(
        value_px=16,
        name="Spacing Medium",
        confidence=0.9,
        semantic_role="padding",
        role="md",
        grid_aligned=True,
        provenance={"image_2": 0.9},
        responsive_scales={"lg": 24},
    )
    library = SpacingTokenLibrary(
        tokens=[token],
        statistics={
            "spacing_count": 1,
            "scale_system": "8pt",
            "base_unit": 8,
            "grid_compliance": 100,
        },
    )
    return library


def test_css_generator_includes_variables_and_stats():
    library = _build_color_library()
    generator = CSSTokenGenerator(library)
    output = generator.generate()

    assert ":root" in output
    assert "--color-primary-primary-accent" in output.lower()
    assert "/* Total colors: 1 */" in output
    assert "/* Average confidence: 85.0%" in output


def test_html_demo_generator_renders_swatches_and_stats():
    library = _build_color_library()
    generator = HTMLDemoGenerator(library)
    output = generator.generate()

    assert "<title>Color Token Library</title>" in output
    assert "Primary Accent" in output
    assert "total colors" in output.lower()


def test_react_generator_exports_collection_and_helpers():
    library = _build_color_library()
    generator = ReactTokenGenerator(library)
    output = generator.generate()

    assert "export const colors = {" in output
    assert "Primary Accent" in output
    assert "export type Colors" in output
    assert "export const getColor" in output
    assert "total colors: 1" in output.lower()


def test_spacing_css_generator_outputs_variables_with_comments():
    library = _build_spacing_library()
    generator = SpacingCSSGenerator(library, prefix="spacing", unit="px", include_comments=True)
    output = generator.generate()

    assert ":root {" in output
    assert "Spacing Scale - 8pt" in output
    assert "--spacing-md" in output
    assert "--spacing-md-rem" in output


def test_spacing_react_generator_produces_helpers_and_exports():
    library = _build_spacing_library()
    generator = SpacingReactGenerator(library, export_name="spacing")
    output = generator.generate()

    assert "export const spacing =" in output
    assert "getSpacing(" in output
    assert "spacingTokens" in output
    assert "Generated by Copy That" in output


def test_spacing_w3c_generator_includes_metadata_and_extensions():
    library = _build_spacing_library()
    generator = SpacingW3CGenerator(library, include_rem=True, include_metadata=True)
    payload = json.loads(generator.generate())

    assert "spacing" in payload
    spacing_section = payload["spacing"]
    assert "$description" in spacing_section
    md = spacing_section["md"]
    assert md["$value"] == "16px"
    assert "$extensions" in md
    ext = md["$extensions"]["com.copythat.spacing"]
    assert "confidence" in ext
    assert "provenance" in ext
