"""Add color_tokens table

Revision ID: 2025_11_19_001
Revises: c1a36d61036a
Create Date: 2025-11-19 20:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2025_11_19_001'
down_revision: Union[str, Sequence[str], None] = 'c1a36d61036a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('extraction_job_id', sa.Integer(), nullable=True),
    sa.Column('hex', sa.String(length=7), nullable=False),
    sa.Column('rgb', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('semantic_name', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('harmony', sa.String(length=50), nullable=True),
    sa.Column('usage', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('color_tokens')
    # ### end Alembic commands ###
